{inputs, ...}: {
  flake-file.inputs.treefmt-nix = {
    url = "github:numtide/treefmt-nix";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  imports = [
    inputs.treefmt-nix.flakeModule
  ];

  perSystem.treefmt = {
    projectRootFile = "flake.lock";

    programs = {
      alejandra.enable = true;
      stylua.enable = true;
      shfmt.enable = true;
    };

    settings.global.excludes = [
      "*/npins/*"
      "**/pnpm-lock.yaml"
      "skills-lock.json"
      # Generated by `nix run .#write-flake`; formatting it would be
      # reverted on the next regeneration.
      "flake.nix"
    ];
  };
}
